version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sgz111
      MYSQL_DATABASE: upc
      #MYSQL_USER: upc
      #MYSQL_PASSWORD: sgz111
    ports:
      - 13306:3306
    volumes:
      - ./data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080